#!/bin/sh

OS="$(uname)"
BUILD_FOLDER_NAME="build"
BASE_PATH="$(pwd)"
BUILDER_TYPE=$1

XCODE_PATH="${BASE_PATH}/${BUILD_FOLDER_NAME}.xcode"
NINJA_PATH="${BASE_PATH}/${BUILD_FOLDER_NAME}.ninja"
MAKE_PATH="${BASE_PATH}/${BUILD_FOLDER_NAME}.make"

if [ "${OS}" = "Darwin" ] && [ ! -z "$(which xcodebuild)" ] && [ -z "${BUILDER_TYPE}" ] || [ "${BUILDER_TYPE}" = "xcode" ]; then
    rm -rf ${XCODE_PATH}
    mkdir ${XCODE_PATH}
    cd ${XCODE_PATH}
    cmake .. -GXcode
    touch AUTOGENERATED
    cd ..
fi

if [ ! -z "$(which ninja)" ] && [ -z ${BUILDER_TYPE} ] && [ -z "${BUILDER_TYPE}" ] || [ "${BUILDER_TYPE}" = "ninja" ]; then
    rm -rf ${NINJA_PATH}
    mkdir ${NINJA_PATH}
    cd ${NINJA_PATH}
    cmake .. -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=1
    touch AUTOGENERATED
    cd ..
fi

if [ ! -z "$(which make)" ] && [ -z ${BUILDER_TYPE} ] && [ -z "${BUILDER_TYPE}" ] || [ "${BUILDER_TYPE}" = "make" ]; then
    rm -rf ${MAKE_PATH}
    mkdir ${MAKE_PATH}
    cd ${MAKE_PATH}
    cmake .. -G"Unix Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=1
    touch AUTOGENERATED
    cd ..
fi
